checks:
  php: true

filter:
  paths:
    - "src/*"

build:
  image: default-bionic

  environment:
    php:
      version: 8.0.11
      ini:
        "xdebug.mode": coverage

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
